site_name: My Portfolio
theme:
  name: mkdocs
nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Project 1: projects/project1.md
      - Project 2: projects/project2.md
plugins:
  - search
